import { DEFAULT_DISABLED_BUILTIN_AGENTS, DEFAULT_PUBLIC_AGENTS, ROUTER_AGENT_CATALOG } from "./agent-catalog.js"

function inlineList(values = []) {
  return values.join("; ")
}

export function buildAgentsDocument() {
  const lines = [
    "# AGENTS",
    "",
    "_Generated by `scripts/generate-agents-doc.js`. Do not hand-edit._",
    "",
    "## System Shape",
    "",
    "- `mic` is the persistent intake window.",
    "- `pi` is the execution foreman.",
    "- `snap` remains a low-ceremony direct-action entry.",
    "- All other router agents are backstage specialists.",
    "- Runtime agent defaults come from `src/agent-catalog.js`.",
    "- Mic presentation sources live under `src/presentation/mic-intake/`; the small barrel `src/presentation/mic-intake-spec.js` only re-exports them.",
    "- Command presentation sources live under `src/presentation/commands/`; the small barrel `src/presentation/command-views.js` only re-exports them.",
    "- Mic parser acceptance rules live separately in `src/intake-parser-contract.js` and `src/intake.js`.",
    "- Prompt authoring sources live in `prompts/` and are bundled into `src/prompt-registry.js`.",
    "",
    "## Runtime Defaults",
    "",
    `- Public agents: ${DEFAULT_PUBLIC_AGENTS.map((value) => `\`${value}\``).join(", ")}`,
    `- Disabled builtin agents in managed mode: ${DEFAULT_DISABLED_BUILTIN_AGENTS.map((value) => `\`${value}\``).join(", ")}`,
    "",
    "## Prompt Authoring Rules",
    "",
    "- Keep each prompt split conceptually into role, mission, activation, boundaries, input contract, operating rules, and output contract.",
    "- Do not duplicate Mic card shape, output UX style, or canonical intake samples inside prompt prose; keep those under `src/presentation/mic-intake/`.",
    "- When changing visible Mic output shape/style, edit the presentation files first; only touch parser files when the machine-readable contract truly changes.",
    "- Do not duplicate command output shape/style inside command logic; keep `/pi-dispatch`, `/pi-rematch*`, `/pi-up`, and `/pi-book` renderers under `src/presentation/commands/`.",
    "- Do not duplicate router agent role summaries manually when a shared catalog fragment can generate them.",
    "- After editing `prompts/`, `src/agent-catalog.js`, or Mic presentation sources under `src/presentation/mic-intake/`, regenerate bundled assets.",
    "",
    "## Agent Directory",
    "",
  ]

  for (const agent of Object.values(ROUTER_AGENT_CATALOG)) {
    lines.push(`### \`${agent.id}\` · ${agent.label}`)
    lines.push("")
    lines.push(`- Mode: \`${agent.mode}\``)
    lines.push(`- Surface: ${agent.surface}`)
    lines.push(`- Prompt source: \`${agent.prompt_source}\``)
    lines.push(`- Description: ${agent.description}`)
    lines.push(`- Mission: ${agent.mission}`)
    lines.push(`- Cost posture: ${agent.cost_posture}`)
    lines.push(`- Best use cases: ${inlineList(agent.use_cases)}`)
    lines.push(`- Avoid when: ${inlineList(agent.avoid_when)}`)
    lines.push(`- Default output sections: ${inlineList(agent.output_sections.map((item) => `\`${item}\``))}`)
    if (Object.keys(agent.permission || {}).length > 0) {
      lines.push(`- Permission overrides: \`${JSON.stringify(agent.permission)}\``)
    }
    lines.push("")
  }

  lines.push("## Maintenance")
  lines.push("")
  lines.push("- Regenerate prompt bundle: `node scripts/generate-prompt-registry.js`")
  lines.push("- Regenerate Mic fixtures: `node scripts/generate-intake-fixtures.js`")
  lines.push("- Regenerate agent directory: `node scripts/generate-agents-doc.js`")
  lines.push("- Full sync: `npm run sync-agent-surfaces`")
  lines.push("- Drift check: `node scripts/check-generated-assets.js`")
  lines.push("")

  return `${lines.join("\n")}\n`
}
