name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Nub with Node.js ${{ matrix.node-version }}
        uses: nubjs/setup-nub@v0
        with:
          node-version: ${{ matrix.node-version }}
      - run: nub install
      - run: nub run test
      - run: nub run check:beta
